repos:
  - repo: local
    hooks:
      - id: generate_readme
        name: GenerateReadme
        entry: python GENERATE_README.py
        language: system
        types: [python]
        always_run: true
  - repo: local
    hooks:
      - id: stage_all_updates
        name: StageAllUpdates
        entry: git add .
        language: system
        always_run: true
